---
dependencies: []

galaxy_info:
  role_name: ludus_mde_agent
  author: rstephenson
  description: An Ansible Role that installs the MDE agent on Windows and onboards it to the security portal.
  company: ''
  license: GPLv3
  min_ansible_version: "2.10"
  platforms:
    # Modify the platforms here as required
    # This example includes a lot, see https://github.com/ansible/ansible-lint/blob/main/src/ansiblelint/schemas/meta.json for all possibilities
    - name: Windows 
      versions:
        - "2025"
        - "2022"
        - "2019"
        - "all"
  galaxy_tags:
    - ansible
    - ansible-role
    - mde
    - defender
    - endpoint
    - security
    - windows

collections: [] # Add any collections needed here
